"""Add image_filename column

Revision ID: 577cbc959edf
Revises: 
Create Date: 2025-03-21 11:22:13.798501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577cbc959edf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
